// Soru modeli ve tüm sorular

export type SoruTuru = 'metin' | 'sayi' | 'tekSecim' | 'cokluSecim' | 'uzunMetin';

export interface Soru {
  numara: number;
  kategori: string;
  soruMetni: string;
  ipucu: string;
  alanAdi: string;
  tur: SoruTuru;
  secenekler?: string[];
}

export const SORULAR: Soru[] = [
  // TEMEL BİLGİLER (1-8)
  {
    numara: 1,
    kategori: "Temel Bilgiler",
    soruMetni: "Adı neydi?",
    ipucu: "Örn: Ayşe, Mehmet, Can",
    alanAdi: "isim",
    tur: "metin",
  },
  {
    numara: 2,
    kategori: "Temel Bilgiler",
    soruMetni: "Sana nasıl hitap ederdi?",
    ipucu: "Örn: Aşkım, Bebeğim, Canım, adınla mı?",
    alanAdi: "sana_hitap",
    tur: "metin",
  },
  {
    numara: 3,
    kategori: "Temel Bilgiler",
    soruMetni: "Sen ona nasıl hitap ederdin?",
    ipucu: "Örn: Tatlım, Aşkım, Hayatım",
    alanAdi: "sen_ona_hitap",
    tur: "metin",
  },
  {
    numara: 4,
    kategori: "Temel Bilgiler",
    soruMetni: "Kaç yaşındaydı?",
    ipucu: "Örn: 24",
    alanAdi: "yas",
    tur: "sayi",
  },
  {
    numara: 5,
    kategori: "Temel Bilgiler",
    soruMetni: "Ne iş yapıyordu / ne okuyordu?",
    ipucu: "Örn: Mühendis, Üniversite öğrencisi, Öğretmen",
    alanAdi: "meslek",
    tur: "metin",
  },
  {
    numara: 6,
    kategori: "Temel Bilgiler",
    soruMetni: "Ses tonu nasıldı?",
    ipucu: "Mesajlarındaki genel havayı düşün",
    alanAdi: "ses_tonu",
    tur: "tekSecim",
    secenekler: ["Yumuşak", "Enerjik", "Sakin", "Heyecanlı", "Neşeli", "Ciddi", "Tatlı"],
  },
  {
    numara: 7,
    kategori: "Temel Bilgiler",
    soruMetni: "Ne kadar süre birliktediniz?",
    ipucu: "Örn: 2 yıl, 6 ay, 3 yıl",
    alanAdi: "birlikte_sure",
    tur: "metin",
  },
  {
    numara: 8,
    kategori: "Temel Bilgiler",
    soruMetni: "Onu temsil edecek bir emoji seç",
    ipucu: "Bu emoji profil resmi olarak kullanılacak",
    alanAdi: "profil_emoji",
    tur: "tekSecim",
    secenekler: ["💜", "💙", "💚", "🧡", "💛", "🤍", "🖤", "💗", "🌸", "🌙", "⭐", "🦋", "🌹", "🔥", "✨"],
  },

  // İLETİŞİM TARZI (9-18)
  {
    numara: 9,
    kategori: "İletişim Tarzı",
    soruMetni: "Mesajları uzun mu yazardı kısa mı?",
    ipucu: "Genel mesajlaşma tarzını düşün",
    alanAdi: "mesaj_uzunlugu",
    tur: "tekSecim",
    secenekler: ["Çok kısa (1-2 kelime)", "Kısa", "Orta", "Uzun", "Çok uzun (paragraflar)"],
  },
  {
    numara: 10,
    kategori: "İletişim Tarzı",
    soruMetni: "En çok kullandığı emojiler hangileri?",
    ipucu: "En fazla 5 tane seç",
    alanAdi: "favori_emojiler",
    tur: "cokluSecim",
    secenekler: ["😊", "😂", "🥺", "❤️", "😘", "🙈", "😍", "🤣", "💕", "😭", "🥰", "😋", "🤗", "😏", "🙄", "😅", "💜", "✨", "🔥", "👀"],
  },
  {
    numara: 11,
    kategori: "İletişim Tarzı",
    soruMetni: "Nasıl gülerdi yazarken?",
    ipucu: "Örn: hahaha, jsjsjs, 😂😂, sksksk, ahaha",
    alanAdi: "gulme_stili",
    tur: "metin",
  },
  {
    numara: 12,
    kategori: "İletişim Tarzı",
    soruMetni: "Sabahları ilk mesajı nasıl olurdu?",
    ipucu: "Örn: Günaydın aşkım 🌅, Kalktın mı tatlım?",
    alanAdi: "sabah_mesaji",
    tur: "metin",
  },
  {
    numara: 13,
    kategori: "İletişim Tarzı",
    soruMetni: "Gece yatmadan nasıl mesaj atardı?",
    ipucu: "Örn: İyi geceler canım 🌙, Rüyamda ol",
    alanAdi: "gece_mesaji",
    tur: "metin",
  },
  {
    numara: 14,
    kategori: "İletişim Tarzı",
    soruMetni: "Seni özlediğinde nasıl ifade ederdi?",
    ipucu: "Örn: Çok özledim seni ya, Yanımda olsan keşke",
    alanAdi: "ozlem_ifadesi",
    tur: "uzunMetin",
  },
  {
    numara: 15,
    kategori: "İletişim Tarzı",
    soruMetni: "Kızgın veya üzgün olduğunda nasıl yazardı?",
    ipucu: "Örn: Noktalama kullanmaz, tek kelime cevaplar verir",
    alanAdi: "kizgin_tarzi",
    tur: "uzunMetin",
  },
  {
    numara: 16,
    kategori: "İletişim Tarzı",
    soruMetni: "Şakalaşırken nasıl bir tarzı vardı?",
    ipucu: "Örn: Kara mizah, tatlı espriler, taşlama yapardı",
    alanAdi: "saka_stili",
    tur: "metin",
  },
  {
    numara: 17,
    kategori: "İletişim Tarzı",
    soruMetni: "Sana en çok sorduğu soru neydi?",
    ipucu: "Örn: Ne yapıyorsun?, Beni seviyor musun?, Yemek yedin mi?",
    alanAdi: "sik_sorulan_soru",
    tur: "metin",
  },
  {
    numara: 18,
    kategori: "İletişim Tarzı",
    soruMetni: "Sık kullandığı kelimeler veya kalıplar?",
    ipucu: "Örn: ya, işte, hani, bak şimdi",
    alanAdi: "sik_kullanilan",
    tur: "metin",
  },

  // DUYGUSAL İFADELER (19-28)
  {
    numara: 19,
    kategori: "Duygusal İfadeler",
    soruMetni: '"Seni seviyorum"u nasıl söylerdi?',
    ipucu: "Örn: Seni çok seviyorum, Aşkımsın, Deliler gibi seviyorum",
    alanAdi: "seni_seviyorum",
    tur: "metin",
  },
  {
    numara: 20,
    kategori: "Duygusal İfadeler",
    soruMetni: "Seni teselli ederken ne derdi?",
    ipucu: "Örn: Üzme yanındayım, Her şey güzel olacak",
    alanAdi: "teselli_tarzi",
    tur: "uzunMetin",
  },
  {
    numara: 21,
    kategori: "Duygusal İfadeler",
    soruMetni: "Seninle gurur duyduğunda nasıl ifade ederdi?",
    ipucu: "Örn: Çok gururluyum seninle, Benim aslanım",
    alanAdi: "gurur_ifadesi",
    tur: "metin",
  },
  {
    numara: 22,
    kategori: "Duygusal İfadeler",
    soruMetni: "Kıskançlık gösterdiğinde nasıl davranırdı?",
    ipucu: "Örn: Kim o?, Niye onunla konuşuyorsun?",
    alanAdi: "kiskanclik_tarzi",
    tur: "uzunMetin",
  },
  {
    numara: 23,
    kategori: "Duygusal İfadeler",
    soruMetni: "Özür dilediğinde nasıl cümleler kurardı?",
    ipucu: "Örn: Özür dilerim hatalıyım, Kızma bana ya",
    alanAdi: "ozur_tarzi",
    tur: "uzunMetin",
  },
  {
    numara: 24,
    kategori: "Duygusal İfadeler",
    soruMetni: "Sana iltifat ederken en çok ne derdi?",
    ipucu: "Örn: Çok güzelsin, Çok tatlısın, Çok akıllısın",
    alanAdi: "iltifat_tarzi",
    tur: "metin",
  },
  {
    numara: 25,
    kategori: "Duygusal İfadeler",
    soruMetni: "Senden bir şey istediğinde nasıl söylerdi?",
    ipucu: "Örn: Direkt söyler, nazlanır, ima eder",
    alanAdi: "istek_tarzi",
    tur: "metin",
  },
  {
    numara: 26,
    kategori: "Duygusal İfadeler",
    soruMetni: "Mutlu olduğunda nasıl belli ederdi?",
    ipucu: "Örn: Çok emoji kullanır, uzun mesajlar atar",
    alanAdi: "mutlu_tarzi",
    tur: "metin",
  },
  {
    numara: 27,
    kategori: "Duygusal İfadeler",
    soruMetni: "Endişelendiğinde nasıl konuşurdu?",
    ipucu: "Örn: Sürekli sorar, kontrol eder, sessizleşir",
    alanAdi: "endise_tarzi",
    tur: "uzunMetin",
  },
  {
    numara: 28,
    kategori: "Duygusal İfadeler",
    soruMetni: "Seni motive etmek istediğinde ne söylerdi?",
    ipucu: "Örn: Sen yaparsın, İnanıyorum sana",
    alanAdi: "motivasyon_tarzi",
    tur: "uzunMetin",
  },

  // İLGİ ALANLARI (29-38)
  {
    numara: 29,
    kategori: "İlgi Alanları",
    soruMetni: "En sevdiği yemek neydi?",
    ipucu: "Örn: Makarna, Pizza, Lahmacun",
    alanAdi: "favori_yemek",
    tur: "metin",
  },
  {
    numara: 30,
    kategori: "İlgi Alanları",
    soruMetni: "Hangi müzikleri dinlerdi?",
    ipucu: "Örn: Pop, Rap, Arabesk, Rock",
    alanAdi: "favori_muzik",
    tur: "metin",
  },
  {
    numara: 31,
    kategori: "İlgi Alanları",
    soruMetni: "Favori filmi veya dizisi neydi?",
    ipucu: "Örn: Friends, Kore dizileri, Marvel filmleri",
    alanAdi: "favori_film",
    tur: "metin",
  },
  {
    numara: 32,
    kategori: "İlgi Alanları",
    soruMetni: "Boş zamanlarında ne yapmayı severdi?",
    ipucu: "Örn: Oyun oynamak, kitap okumak, gezmek",
    alanAdi: "hobiler",
    tur: "metin",
  },
  {
    numara: 33,
    kategori: "İlgi Alanları",
    soruMetni: "En çok ne hakkında konuşmayı severdi?",
    ipucu: "Örn: Gelecek planları, dedikodu, iş/okul",
    alanAdi: "konusma_konulari",
    tur: "metin",
  },
  {
    numara: 34,
    kategori: "İlgi Alanları",
    soruMetni: "Hangi konularda tutkulu/heyecanlıydı?",
    ipucu: "Örn: Futbol, moda, teknoloji, hayvanlar",
    alanAdi: "tutkulari",
    tur: "metin",
  },
  {
    numara: 35,
    kategori: "İlgi Alanları",
    soruMetni: "Nelerden şikayet ederdi?",
    ipucu: "Örn: İş stresi, ailesi, trafik",
    alanAdi: "sikayetleri",
    tur: "metin",
  },
  {
    numara: 36,
    kategori: "İlgi Alanları",
    soruMetni: "Hangi konularda seninle aynı fikirde değildi?",
    ipucu: "Örn: Siyaset, arkadaş seçimi, para harcama",
    alanAdi: "anlasmazliklar",
    tur: "metin",
  },
  {
    numara: 37,
    kategori: "İlgi Alanları",
    soruMetni: "Birlikte en çok ne yapardınız?",
    ipucu: "Örn: Film izlemek, gezmek, yemek yemek",
    alanAdi: "birlikte_yapilanlar",
    tur: "metin",
  },
  {
    numara: 38,
    kategori: "İlgi Alanları",
    soruMetni: "Size özel bir şakanız veya anınız var mıydı?",
    ipucu: "Sadece ikinizin anladığı bir espri veya olay",
    alanAdi: "ozel_sakalar",
    tur: "uzunMetin",
  },

  // KİŞİLİK ÖZELLİKLERİ (39-45)
  {
    numara: 39,
    kategori: "Kişilik",
    soruMetni: "Genel olarak iyimser miydi kötümser mi?",
    ipucu: "Hayata bakış açısını düşün",
    alanAdi: "iyimserlik",
    tur: "tekSecim",
    secenekler: ["Çok iyimser", "İyimser", "Dengeli", "Kötümser", "Çok kötümser"],
  },
  {
    numara: 40,
    kategori: "Kişilik",
    soruMetni: "Planlı biri miydi yoksa spontane mi?",
    ipucu: "Ani kararlar mı verirdi, her şeyi planlar mıydı",
    alanAdi: "plancilik",
    tur: "tekSecim",
    secenekler: ["Çok planlı", "Planlı", "Karma", "Spontane", "Çok spontane"],
  },
  {
    numara: 41,
    kategori: "Kişilik",
    soruMetni: "Duygularını açıkça ifade eder miydi?",
    ipucu: "Duygularını belli eder miydi",
    alanAdi: "duygusal_ifade",
    tur: "tekSecim",
    secenekler: ["Çok açık", "Açık", "Orta", "Kapalı", "Çok kapalı"],
  },
  {
    numara: 42,
    kategori: "Kişilik",
    soruMetni: "Romantik miydi pragmatik mi?",
    ipucu: "Duygusal mı mantıksal mı yaklaşırdı",
    alanAdi: "romantiklik",
    tur: "tekSecim",
    secenekler: ["Çok romantik", "Romantik", "Dengeli", "Pragmatik", "Çok pragmatik"],
  },
  {
    numara: 43,
    kategori: "Kişilik",
    soruMetni: "Sosyal biri miydi içe dönük mü?",
    ipucu: "İnsanlarla ilişkisini düşün",
    alanAdi: "sosyallik",
    tur: "tekSecim",
    secenekler: ["Çok sosyal", "Sosyal", "Dengeli", "İçe dönük", "Çok içe dönük"],
  },
  {
    numara: 44,
    kategori: "Kişilik",
    soruMetni: "Stresli anlarda nasıl tepki verirdi?",
    ipucu: "Örn: Sessizleşir, bağırır, ağlar, uzaklaşır",
    alanAdi: "stres_tepkisi",
    tur: "uzunMetin",
  },
  {
    numara: 45,
    kategori: "Kişilik",
    soruMetni: "En sevdiğin özelliği neydi?",
    ipucu: "Örn: Gülüşü, anlayışı, zekası, enerjisi",
    alanAdi: "en_iyi_ozellik",
    tur: "metin",
  },

  // ÖZEL ANILAR (46-50)
  {
    numara: 46,
    kategori: "Özel Anılar",
    soruMetni: "Sana söylediği ve hiç unutmadığın bir cümle?",
    ipucu: "Kalbine kazınan, seni etkileyen bir söz",
    alanAdi: "unutulmaz_cumle",
    tur: "uzunMetin",
  },
  {
    numara: 47,
    kategori: "Özel Anılar",
    soruMetni: "Onunla ilgili en çok özlediğin şey ne?",
    ipucu: "Örn: Gülüşü, dokunuşu, sesi, bakışları",
    alanAdi: "en_cok_ozlenen",
    tur: "uzunMetin",
  },
  {
    numara: 48,
    kategori: "Özel Anılar",
    soruMetni: "Birlikte yaşadığınız en güzel anı?",
    ipucu: "Kısaca anlat - en mutlu olduğunuz an",
    alanAdi: "en_guzel_ani",
    tur: "uzunMetin",
  },
  {
    numara: 49,
    kategori: "Özel Anılar",
    soruMetni: "Size özel bir lakap veya kelime var mıydı?",
    ipucu: "Sadece ikinizin kullandığı özel bir şey",
    alanAdi: "ozel_lakap",
    tur: "metin",
  },
  {
    numara: 50,
    kategori: "Özel Anılar",
    soruMetni: "Onu tanımlayan 3 kelime söyle",
    ipucu: "Örn: Sevecen, komik, inatçı",
    alanAdi: "uc_kelime",
    tur: "metin",
  },
];

export const KATEGORILER = [
  "Temel Bilgiler",
  "İletişim Tarzı",
  "Duygusal İfadeler",
  "İlgi Alanları",
  "Kişilik",
  "Özel Anılar",
];
